In [4]:
# Example of 1 dimensional array

import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))                 #Type of array is ndarray

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

# 🔹 0D ARRAY (Scalar value)
arr_0 = np.array(25)

# Explanation:
# Aa ek single value che → koi list nathi
# Shape: ()
# Indexing:
# arr_0 → 25 (direct value, koi index nathi)
print(f"0 dimensional array : {arr_0}")


# 🔹 1D ARRAY (Vector)
arr_1 = np.array([1,2,3,4,5,6,7,8])

# Explanation:
# [1,2,3,...] → Python list che
# np.array() → ene convert kari ne NumPy array banave che
# Final result → 1D NumPy array
# Shape: (8,)
# Indexing:
# arr_1[0] → 1
# arr_1[3] → 4
# arr_1[7] → 8
print(f"1 Dimensional array : {arr_1}")


# 🔹 2D ARRAY (Matrix)
arr_2 = np.array([[1,2,3],[4,5,6]])

# Explanation:
# Aa list ni andar list che → rows & columns
# Shape: (2, 3)

# Structure:
# Row 0 → [1,2,3]
# Row 1 → [4,5,6]

# Indexing:
# arr_2[0][0] → 1
# arr_2[0][2] → 3
# arr_2[1][1] → 5
print(f"2 dimensional array : {arr_2}")


# 🔹 3D ARRAY (Clear numbers used)
arr_3 = np.array([
    [[1,2,3],[4,5,6]],      # Block 0
    [[7,8,9],[10,11,12]]    # Block 1
])

# Explanation:
# Aa 2D arrays ne ek saathe mukya che → 3D array
# Shape: (2, 2, 3)

# Structure:
# Block 0:
#   Row 0 → [1,2,3]
#   Row 1 → [4,5,6]
#
# Block 1:
#   Row 0 → [7,8,9]
#   Row 1 → [10,11,12]

# Indexing (now easy to understand):
# arr_3[0][0][0] → 1
# arr_3[0][1][2] → 6
# arr_3[1][0][1] → 8
# arr_3[1][1][2] → 12

print(f"3d array : {arr_3}")

0 dimensional array : 25
1 Dimensional array : [1 2 3 4 5 6 7 8]
2 dimensional array : [[1 2 3]
 [4 5 6]]
3d array : [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## __1. Attributes of NumPy Arrays__ ##

A few commonly used attributes of NumPy array include:

In [14]:
import numpy as np

# 🔹 2D ARRAY (Matrix banavyu)
arr_2 = np.array([[1,2,3],[4,5,6]])

# Aa array ma:
# Row 0 → [1,2,3]
# Row 1 → [4,5,6]
# So shape → (2 rows, 3 columns)

print(arr_2)


# 🔹 astype() → data type change kare
arr = arr_2.astype(np.int8)

# Explanation:
# arr_2 original array che (default int64 hoy che)
# astype(np.int8) → new array (arr) banse with smaller data type
# NOTE: arr_2 change thatu nathi, navi copy (arr) banse


# 🔹 ndim → number of dimensions
print(arr_2.ndim)
# Output: 2
# Matlab: aa 2D array che (rows + columns)


# 🔹 shape → structure of array
print(arr_2.shape)
# Output: (2, 3)
# Matlab: 2 rows ane 3 columns


# 🔹 size → total elements
print(arr_2.size)
# Output: 6
# Calculation: 2 × 3 = 6 elements


# 🔹 dtype → data type of elements
print(arr_2.dtype)
# Output: int64 (system par depend kare)
# Matlab: badha values integer type na che


# 🔹 itemsize → ek element ketla bytes le che
print(arr_2.itemsize)
# Output: 8 (for int64)
# Matlab: 1 element = 8 bytes memory


# 🔹 data → memory location (address)
print(arr_2.data)
# Output: <memory at 0x...>
# Matlab: array memory ma kya store che (advanced concept)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
8


## __2. NumPy Array Functions__ ##

In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

new_arr = arr.reshape(4,3)
print(new_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
# Converting a multidimensional(3D) array into a 1D array
# Example 1
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flattened_array = arr3D.flatten()
print(f"Flatten : {flattened_array}")

# Example 2
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
flat_arr = arr.flatten()
print(f"Flatten : {flat_arr}")

Flatten : [ 1  2  3  4  5  6  7  8  9 10 11 12]
Flatten : [ 1  2  3  4  5  6  7  8  9 10 11 12]


### Transpose

In [24]:
# Transpose

arr_2 = np.array([[1,2,3],[4,5,6]])
print(f"Normal matric :\n {arr_2}")

new_trans = arr_2.transpose()
print(f"After Transpose :\n{new_trans}")

Normal matric :
 [[1 2 3]
 [4 5 6]]
After Transpose :
[[1 4]
 [2 5]
 [3 6]]


In [25]:
# ================================
# 3D TRANSPOSE EXPLANATION (NUMPY)
# ================================


# Step 1: Create a 3D array
a = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("Original Array:")
print(a)

print("\nShape of original array:", a.shape)

# --------------------------------
# Step 2: Understanding axes
# --------------------------------
# Shape = (2, 2, 3)
# Axis 0 → Blocks (2 matrices)
# Axis 1 → Rows (2 rows)
# Axis 2 → Columns (3 columns)

print("\nAxis Meaning:")
print("Axis 0 = Blocks")
print("Axis 1 = Rows")
print("Axis 2 = Columns")

# --------------------------------
# Visualizing blocks
# --------------------------------
print("\nBlock 0:\n", a[0])
print("\nBlock 1:\n", a[1])

# --------------------------------
# Case 1: transpose((0, 2, 1))
# --------------------------------
# Swap rows and columns inside each block

result1 = a.transpose((0, 2, 1))

print("\n\nCase 1: transpose((0, 2, 1))")
print("Explanation: Blocks same, Rows ↔ Columns")
print("New Shape:", result1.shape)
print(result1)

# --------------------------------
# Case 2: transpose((2, 1, 0))
# --------------------------------
# Columns become first axis

result2 = a.transpose((2, 1, 0))

print("\n\nCase 2: transpose((2, 1, 0))")
print("Explanation: Columns → Axis 0, Blocks → Axis 2")
print("New Shape:", result2.shape)
print(result2)

# --------------------------------
# Case 3: transpose((1, 0, 2))
# --------------------------------
# Swap blocks and rows

result3 = a.transpose((1, 0, 2))

print("\n\nCase 3: transpose((1, 0, 2))")
print("Explanation: Rows ↔ Blocks")
print("New Shape:", result3.shape)
print(result3)

# --------------------------------
# Important Rule
# --------------------------------
print("\n\nIMPORTANT RULE:")
print("transpose(axes) = reorder axes")
print("New shape = old shape rearranged according to axes")

# --------------------------------
# Quick Practice for Students
# --------------------------------
print("\n\nPRACTICE QUESTION:")
print("What will be the shape of a.transpose((2, 0, 1)) ?")

practice = a.transpose((2, 0, 1))
print("Answer:", practice.shape)

# --------------------------------
# Final Teaching Insight
# --------------------------------
print("\n\nFINAL INSIGHT:")
print("Transpose does NOT change data.")
print("It only changes how we VIEW the data (axes rearrangement).")

Original Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape of original array: (2, 2, 3)

Axis Meaning:
Axis 0 = Blocks
Axis 1 = Rows
Axis 2 = Columns

Block 0:
 [[1 2 3]
 [4 5 6]]

Block 1:
 [[ 7  8  9]
 [10 11 12]]


Case 1: transpose((0, 2, 1))
Explanation: Blocks same, Rows ↔ Columns
New Shape: (2, 3, 2)
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


Case 2: transpose((2, 1, 0))
Explanation: Columns → Axis 0, Blocks → Axis 2
New Shape: (3, 2, 2)
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


Case 3: transpose((1, 0, 2))
Explanation: Rows ↔ Blocks
New Shape: (2, 2, 3)
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


IMPORTANT RULE:
transpose(axes) = reorder axes
New shape = old shape rearranged according to axes


PRACTICE QUESTION:
What will be the shape of a.transpose((2, 0, 1)) ?
Answer: (3, 2, 2)


FINAL INSIGHT:
Transpose does NOT change data.
It only changes how we VIEW the data (axes rearrangement).


In [37]:
a = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(a.shape)   # Fetched a old shape (2,2,3)
new_arr = a.transpose(1,2,0)     # Here we have transpose block,row,column  to ROW,COLUMN,BLOCK
print(new_arr)


(2, 2, 3)
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


### Arithmetic Operations using Numpy

#### 1.1 Addition

In [39]:
# Perform element-wise addition of two arrays using the 'np.add' method
import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([10,20,20,20,20])

result = np.add(a,b)
print(result)


[20 40 50 60 70]


#### 1.2 Subtraction

In [44]:
a = np.array([10,20,30,40,50])
b = np.array([10,20,20,20,20])

result = np.subtract(a,b)
print(result)

apple = np.array([[50,30,10],[60,70,80]])
mango = np.array([[20,20,5],[30,50,20]])

result_sub = np.subtract(apple,mango)
print(result_sub)

[ 0  0 10 20 30]
[[30 10  5]
 [30 20 60]]


#### 1.3 Multiplication

In [45]:
a = np.array([30,20,40,50])
b = np.array([10,15,35,40])

result = np.multiply(a,b)
print(result)

[ 300  300 1400 2000]


#### 1.4 Division

In [46]:
a = np.array([[30,40,50],[60,70,80]])
b = np.array([3,4,5])

result = np.divide(a,b)
print(result)

[[10.  10.  10. ]
 [20.  17.5 16. ]]


#### 1.5 Power

In [47]:
a = np.array([2,3,4,5,6])
b = np.array([2,2,2,3,2])
result = np.power(a,b)
print(result)

[  4   9  16 125  36]


### Statistical Function in Numpy ###
#### 2.1 Calculating Mean,Medium ,Standard deviation and Variance in Array

In [55]:
# Array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Median
np.median(a)
print(np.median(a))

# Mean
np.mean(a)
print(np.mean(a))

# Standard deviation
np.std(a)
print(np.std(a))

# Variance
np.var(a)
print(np.var(a))


5.0
5.0
2.581988897471611
6.666666666666667


#### 2.2 Calculating Percentiles
- The `np.percentile()` function is used to compute the nth percentile of the array elements.
- The nth percentile value should be in between 0 and 100.

In [80]:
import numpy as np

# Create a 1D array
array = np.array([1,2,3,4,5,6,7,8,9])

# np.percentile(array, 50)
# This finds the value below which 50% of the data lies
# In simple words: it gives the middle value (median)
# Sorted array: [1,2,3,4,5,6,7,8,9]
# 50% data lies below 5 → so result = 5

np.percentile(array, 50)


# np.percentile(array, 0)
# This finds the value below which 0% of the data lies
# Means: the smallest value in the array
# So result = 1

# np.percentile(array, 0)


# np.percentile(array, 100)
# This finds the value below which 100% of the data lies
# Means: the largest value in the array
# So result = 9

# np.percentile(array, 100)

np.float64(5.0)

In [82]:
import numpy as np

# Create array
arr = np.array([5,10,15,20])

# np.percentile(arr, 75)
# This finds the value below which 75% of the data lies

# Step 1: Sort the data (already sorted here)
# [5, 10, 15, 20]

# Step 2: Find position using formula:
# position = (n - 1) * (percentile / 100)
# n = 4 → so:
# position = (4 - 1) * 0.75 = 3 * 0.75 = 2.25

# Step 3: Position 2.25 means:
# index 2 → 15
# index 3 → 20
# So value lies between 15 and 20

# Step 4: Interpolation:
# fraction part = 0.25
# value = 15 + (20 - 15) * 0.25
#       = 15 + 5 * 0.25
#       = 15 + 1.25
#       = 16.25

# Final result = 16.25

np.percentile(arr, 75)

np.float64(16.25)

## 3.0 String Function in Numpy

In [85]:
# Add 2 strings

x = np.array(["Hello","Welcome"])
y = np.array([" Ankit"," To the Python"])

result = np.char.add(x,y)
print(result)

['Hello Ankit' 'Welcome To the Python']


In [86]:
# String replace

str = "Hello Ankit How are You ?"

new_string = np.char.replace(str,"Hello","Hi")
print(new_string)

Hi Ankit How are You ?


In [90]:
# Converting strings to Upper Case and Lower Case

str1 = "Hello Ankit How Are You ?"

new_str1 = np.char.upper(str1)
print(new_str1)

str2 = "HELLO PEOPLE WHAT'S UP???"
new_str2 = np.char.lower(str2)
print(new_str2)

HELLO ANKIT HOW ARE YOU ?
hello people what's up???


In [104]:
import numpy as np

# Create a 3D array
# Shape = (2, 2, 3)
# Axis meaning:
# Axis 0 → Blocks (2 blocks)
# Axis 1 → Rows (2 rows in each block)
# Axis 2 → Columns (3 columns in each row)

array_3d = np.array([
    [[1,2,3], [4,5,6]],      # Block 0
    [[7,8,9], [10,11,12]]    # Block 1
])

# Print full array
print(array_3d)

# array_3d[1, :, :2]
# Step-by-step explanation:

# 1 → Select Block 1 (second block)
# Selected:
# [[7,8,9],
#  [10,11,12]]

# : → Select all rows from that block
# Rows remain:
# [[7,8,9],
#  [10,11,12]]

# :2 → Select columns from index 0 up to (but not including) index 2
# So columns 0 and 1 are selected

# Final result:
# [[7,8],
#  [10,11]]

result = array_3d[1, :, :2]

# Print the sliced result
print(f"Sliced Result : {result}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Sliced Result : [[ 7  8]
 [10 11]]


In [106]:
import numpy as np

# Create original array
arr1D = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Slicing creates a VIEW (not a copy)
# a1 is linked to arr1D (same memory reference)
a1 = arr1D[2:5]   # elements: [30, 40, 50]

# Modify the sliced array
a1[0] = 999

# Since a1 is a view, original array also changes
# index 2 (30) becomes 999 in arr1D

print("Original array after slicing modification:", arr1D)

Original array after slicing modification: [ 10  20 999  40  50  60  70  80  90 100]


In [107]:
import numpy as np

# Create original array
arr1D = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# .copy() creates a completely independent array
a2 = arr1D[2:5].copy()   # elements: [30, 40, 50]

# Modify copied array
a2[0] = 999

# Since a2 is a copy, original array will NOT change

print("Copied array:", a2)
print("Original array remains unchanged:", arr1D)

Copied array: [999  40  50]
Original array remains unchanged: [ 10  20  30  40  50  60  70  80  90 100]


In [108]:
import numpy as np

# Create original array
arr1D = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Fancy indexing (using list of indices)
# Always creates a COPY (independent array)
b = arr1D[[2, 3, 4]]   # elements: [30, 40, 50]

# Modify b
b[0] = 555

# Since b is a copy, original array will NOT change

print("Fancy indexed array:", b)
print("Original array remains unchanged:", arr1D)

Fancy indexed array: [555  40  50]
Original array remains unchanged: [ 10  20  30  40  50  60  70  80  90 100]


## NumPy Array Slicing

### __1.1 Slicing 1D NumPy Arrays__

In [127]:
import numpy as np

Employee_rating = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(Employee_rating[4:10])

[ 5  6  7  8  9 10]


#### Example 2: Print the list of three subjects from the fourth index to the end

In [130]:
Subjects = np.array(["Maths","English","Hindi","Science","Gujarati","Statastics","Data Science"])
print(Subjects[4:])


['Gujarati' 'Statastics' 'Data Science']


### __1.2 Slicing Using Step Value__

In [136]:
x= np.array([8,7,6,5,4,3,2,1])
print(x[1:5:3])

[7 4]


### __1.3 Slicing: 2D Array__

In [145]:
a = np.array([[11,22,33,44,55],[66,77,88,99,110]])
print(a[0,2:3])

[33]


### __1.4 Slicing: 3D Array__

In [152]:
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3d[0,1:,1:])

[[5 6]]


### __1.5 Negative Slicing__
- Negative slicing is the same as negative indexing, which is interpreted as counting from the end of the array.

In [157]:
neg_slice = np.array([13,14,15,58,65,85,99])
print(neg_slice[:-1])

[13 14 15 58 65 85]


## __Assisted Practice__

In [1]:
# 1. Create a one-dimensional NumPy array containing at least ten elements

import numpy as np

one_d = np.array([1,2,3,4,5,6,7,8,9,10])
print(one_d)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns

two_d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(two_d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# 3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns

three_d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(three_d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
# 4. Access elements in NumPy arrays and utilize indexing and slicing techniques for efficient data retrieval

three_d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(three_d[0,0,2:])
print(three_d[0,1,1:])

[3]
[5 6]


In [33]:
# 6. Perform and print some basic arithmetic operations (like addition or  subtraction) using elements accessed from 1D, 2D, and 3D arrays
data_1 = np.array([10,20,30,40,50])
data_2 = np.array([5,10,20,30,40])

addition = np.add(data_1,data_2)
subtraction = np.subtract(data_1,data_2)
division = np.divide(data_1,data_2)
multiply = np.multiply(data_1,data_2)

print(f"Addition : {addition}")
print(f"Subtraction : {subtraction}")
print(f"Division : {division}")
print(f"Multiply : {multiply}")

Addition : [15 30 50 70 90]
Subtraction : [ 5 10 10 10 10]
Division : [2.         2.         1.5        1.33333333 1.25      ]
Multiply : [  50  200  600 1200 2000]


In [46]:
# 7. Access and print elements using negative indices in all three arrays

one_d = np.array([1,2,3,4,5,6])
print(one_d[-3:])

two_d = np.array([[1,2,3,4],[5,6,7,8]])
print(two_d[0,-3:-1])

three_d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(three_d[1,0,-3:-1])

[4 5 6]
[2 3]
[10 11]
